"""Write a Digest as `digest.json` + `digest.md` under the run's artifact dir.

Why this lives in `summarization/` (not `observability/artifact_store.py`):
    `artifact_store.write_stage_artifact` serializes `list[SourceItem]`
    — the shape every pre-summarize stage produces. A `Digest` has
    extra fields (intro, model_used, per-entry LLM summaries) that
    don't exist on `SourceItem`, so forcing it through the generic
    writer would either lose those fields or pollute the generic
    writer with Digest-specific branching.

    Keeping the Digest renderer next to the Digest producer means
    "the summarize stage owns the shape of its own artifact". The
    observability layer stays ignorant of Digest, and a future V2
    model (conversation threads, multi-day rollups) can add its own
    artifact helper without touching anything shared.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from ..models.digest import Digest
from ..observability.run_context import RunContext

logger = logging.getLogger(__name__)


def write_digest_artifact(
    rc: RunContext,
    digest: Digest,
    *,
    stage_name: str = "digest",
) -> tuple[Path, Path] | None:
    """Write `<stage>.json` and `<stage>.md` for a Digest.

    Args:
        rc: Run context — provides the artifact directory.
        digest: The fully summarized digest from summarizer.
        stage_name: File stem. Defaults to "digest"; tests or future
            stages can override (e.g. "digest_compressed").

    Returns:
        (json_path, md_path) for logging or tests. Returns None when
        `rc.write_artifacts` is False.

    Called by:
        `pipeline.digest_pipeline` after the summarize stage (M4).
    """
    if not rc.write_artifacts:
        return None
    rc.ensure_dirs()
    json_path = rc.artifact_dir / f"{stage_name}.json"
    md_path = rc.artifact_dir / f"{stage_name}.md"

    json_path.write_text(
        json.dumps(digest.model_dump(mode="json"), ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    md_path.write_text(_render_digest_md(digest), encoding="utf-8")

    logger.info(
        "artifact written stage=%s entries=%d model=%s json=%s md=%s",
        stage_name, len(digest.entries), digest.model_used, json_path, md_path,
    )
    return json_path, md_path


def _render_digest_md(digest: Digest) -> str:
    """Human-readable MD view of a Digest — for skimming during debug."""
    lines = [
        f"# {digest.topic} — {digest.digest_date.isoformat()}",
        "",
        digest.intro.strip() or "_(empty)_",
        "",
    ]
    for i, e in enumerate(digest.entries, start=1):
        if i > 1:
            lines.append("━━━━━━━━━━━━━━━")
            lines.append("")
        marker = "📖" if e.item.full_text_accessible else "📌"
        lines.append(f"## {marker} {i}. {e.item.title}")
        lines.append("")
        lines.append(e.summary.strip() or "_(empty)_")
        lines.append("")
        lines.append(f"🔗 [{e.item.url}]({e.item.url})")
        lines.append("")
    if any(e.item.full_text_accessible for e in digest.entries):
        lines.append("_📖 = full text accessible for follow-up_")
        lines.append("")
    lines.append(f"_✨ Generated by: {digest.model_used}_")
    return "\n".join(lines)
