"""Pure rendering: `Digest` → Telegram HTML string.

Why "pure": no LLM, no network, no SQLite. Same Digest in → same HTML
out, always. This makes length-policy testing easy — just call
`render_digest(digest)` and measure the result.

HTML vs Markdown:
  We use Telegram's HTML parse_mode (set in TelegramConfig). Compared
  to MarkdownV2 it has fewer "characters you must escape or Telegram
  rejects your message" traps. Supported tags we use:
    <b>     bold                (section headers, item titles)
    <a>     clickable link      (source URL at end of each entry)
    <i>     italic              (footer / legend)
  See https://core.telegram.org/bots/api#html-style for the full list.

Structure of the rendered digest:
    <header: 🔬 Topic — Date>

    <intro paragraph, plain text>

    📋 <b>Papers</b>

    📌 1. <b>Title</b>
    🏷 <b>Source</b>  ·  📅 Apr 15  ·  👥 Liu et al.

    <summary paragraph>
    🔗 <a href="url">url</a>

    ━━━━━━━━━━━━━━━

    📌 2. ...

    ✨ <i>Summarized by: model_used</i>
    🤖 <i>Generated by: <a href="github-url">Research-Agent</a></i>

Sections appear only when they have at least one entry. Entries within
a section are already in rank-descending order (set by the summarizer,
which preserved ranking-stage order).

Titles are kept in their original language per user's preference — no
translation is done here, and this file never touches the summary
strings beyond wrapping them into the layout.
"""

from __future__ import annotations

import calendar
import html
from collections import defaultdict

from ..models.digest import Digest, DigestEntry
from ..models.source_item import SourceItem

_SECTION_ORDER: tuple[str, ...] = ("PAPERS", "BLOGS", "PODCASTS", "SOCIAL")
_SECTION_EMOJI: dict[str, str] = {
    "PAPERS": "📋", "BLOGS": "📝", "PODCASTS": "🎙", "SOCIAL": "💬",
}
_SEPARATOR = "━━━━━━━━━━━━━━━"
_META_DOT = "  ·  "
_PROJECT_URL = "https://github.com/Zhenglin17/Research-Agent"


def _esc(text: str) -> str:
    """Escape user/LLM text for HTML parse_mode.

    Telegram HTML requires `&`, `<`, `>` escaped inside text nodes. We
    never put raw LLM output into the message without passing it
    through here — a stray `<` would make Telegram reject the whole
    message with 400 Bad Request.
    """
    return html.escape(text, quote=False)


def source_label(item: SourceItem) -> str:
    """Human-readable source tag for the meta line.

    PubMed and bioRxiv/medRxiv get a short canonical name regardless
    of which specific search/feed they came from — the reader just
    wants to know "this came from PubMed". RSS items use the adapter-
    provided `source_name` (e.g. "Nature Cancer"); if that's missing
    we fall back to the raw `source_id` so we never render an empty
    tag.
    """
    if item.source_type == "pubmed":
        return "PubMed"
    if item.source_type == "biorxiv":
        server = (item.extra or {}).get("server", "biorxiv")
        return "medRxiv" if server == "medrxiv" else "bioRxiv"
    return item.source_name or item.source_id


def short_date(published_iso_date) -> str:  # noqa: ANN001 — datetime.date
    """Format a date as e.g. `Apr 15` — locale-independent.

    Shared between the Telegram renderer and `digest.md` so both
    surfaces show the date in identical form.
    """
    return f"{calendar.month_abbr[published_iso_date.month]} {published_iso_date.day}"


def first_author_short(authors: list[str]) -> str | None:
    """Return "Liu" or "Liu et al." — the compact byline form.

    Extracts a best-effort surname:
      * If the name contains a comma ("Du, J."), use the part before
        the first comma ("Du") — that's the bioRxiv convention.
      * Otherwise take the last whitespace-separated token ("Jiajun
        Liu" → "Liu") — standard "First Last" form from PubMed/RSS.

    Returns None when the list is empty so the caller can omit the
    👥 segment entirely rather than render a blank.
    """
    if not authors:
        return None
    raw = authors[0].strip()
    if not raw:
        return None
    if "," in raw:
        surname = raw.split(",", 1)[0].strip()
    else:
        surname = raw.split()[-1]
    if len(authors) > 1:
        return f"{surname} et al."
    return surname


def _render_meta_line(item: SourceItem) -> str:
    """Second header line: `🏷 Source  ·  📅 Date  ·  👥 Author`.

    Each segment is optional only at its source: date is always set
    (all items have `published_at`), source_label always returns a
    non-empty string, but authors may be empty and that segment gets
    dropped silently.
    """
    parts = [
        f"🏷 <b>{_esc(source_label(item))}</b>",
        f"📅 {short_date(item.published_at.date())}",
    ]
    author = first_author_short(item.authors)
    if author:
        parts.append(f"👥 {_esc(author)}")
    return _META_DOT.join(parts)


def _render_entry(idx: int, entry: DigestEntry) -> str:
    """Render one numbered entry block.

    Args:
        idx: 1-based position inside the section.
        entry: The DigestEntry to render.

    Returns:
        A multi-line HTML string ending WITHOUT a trailing newline.
    """
    item = entry.item
    title = _esc(item.title)
    url = str(item.url)

    marker = "📖" if item.full_text_accessible else "📌"
    title_line = f"{marker} {idx}. <b>{title}</b>"
    meta_line = _render_meta_line(item)
    summary = _esc(entry.summary.strip())
    link_line = f'🔗 <a href="{_esc(url)}">{_esc(url)}</a>'

    return f"{title_line}\n{meta_line}\n\n{summary}\n{link_line}"


def _render_section(section: str, entries: list[DigestEntry]) -> str:
    """Render one section header + its entries, separated by visual dividers."""
    emoji = _SECTION_EMOJI.get(section, "📄")
    header = f"{emoji} <b>{section.title()}</b>"
    rendered = [_render_entry(i, e) for i, e in enumerate(entries, start=1)]
    body = f"\n\n{_SEPARATOR}\n\n".join(rendered)
    return f"{header}\n\n{body}"


def _group_by_section(entries: list[DigestEntry]) -> dict[str, list[DigestEntry]]:
    """Preserve the incoming (rank-ordered) order inside each section."""
    grouped: dict[str, list[DigestEntry]] = defaultdict(list)
    for e in entries:
        grouped[e.section].append(e)
    return grouped


def _ordered_sections(grouped: dict[str, list[DigestEntry]]) -> list[str]:
    """Canonical order first, then any unknown sections at the end."""
    known = [s for s in _SECTION_ORDER if s in grouped]
    unknown = [s for s in grouped if s not in _SECTION_ORDER]
    return known + unknown


def render_header(digest: Digest) -> str:
    """Top-of-message title line. Kept a standalone helper so length
    policy can measure it independently of the body."""
    return f"<b>🔬 {_esc(digest.topic)} — {digest.digest_date.isoformat()}</b>"


def render_footer(digest: Digest) -> str:
    """Bottom attribution block.

    Two lines:
      * "Summarized by: <model>" — the actually-used model, so the
        reader can compare outputs across the `test_models` rotation.
      * "Generated by: <github link>" — link back to the project
        source so a curious reader can see how the digest is built.

    Both are wrapped in <i> for visual separation from the body; the
    project URL is an anchor so Telegram renders it clickable.
    """
    summarized = f"<i>✨ Summarized by: {_esc(digest.model_used)}</i>"
    generated = (
        f'<i>🤖 Generated by: <a href="{_esc(_PROJECT_URL)}">Research-Agent</a></i>'
    )
    return f"{summarized}\n{generated}"


def render_digest(digest: Digest) -> str:
    """Full render: header + intro + sections + footer.

    Args:
        digest: Fully summarized digest from the summarization layer.

    Returns:
        One HTML string ready to pass to the Telegram API. May exceed
        the Telegram 4096-char hard limit — length policy in deliver.py
        handles that; this function doesn't truncate.

    Called by:
        `deliver.prepare_messages`, once per degradation attempt.
    """
    parts: list[str] = [render_header(digest)]
    if digest.intro.strip():
        parts.append(_esc(digest.intro.strip()))

    grouped = _group_by_section(digest.entries)
    for section in _ordered_sections(grouped):
        parts.append(_render_section(section, grouped[section]))

    # Legend appears only when at least one entry got the 📖 marker, so
    # digests with no accessible items don't show an unexplained icon key.
    if any(e.item.full_text_accessible for e in digest.entries):
        parts.append("<i>📖 = full text accessible for follow-up</i>")

    parts.append(render_footer(digest))
    return "\n\n".join(parts)


def render_with_top_n(digest: Digest, n: int) -> str:
    """Render only the top-N entries (by the order already on the digest).

    Used by length-policy degradation Levels 1-2: progressively shrink
    `n` until the rendered message fits, down to `min_items_floor`.
    """
    shrunk = digest.model_copy(update={"entries": digest.entries[:n]})
    return render_digest(shrunk)


def split_message(message: str, hard_limit: int) -> list[str]:
    """Split an over-long HTML message into chunks that each fit under hard_limit.

    Strategy per cut:
      - Try to split at a blank-line boundary (`\\n\\n`) before hard_limit.
      - Fall back to the last single newline before the limit.
      - Last resort: hard character cut.

    Returns `[message]` unchanged if it already fits.
    """
    chunks: list[str] = []
    remaining = message

    while len(remaining) > hard_limit:
        cut = remaining.rfind("\n\n", 0, hard_limit)
        if cut <= 0:
            cut = remaining.rfind("\n", 0, hard_limit)
        if cut <= 0:
            cut = hard_limit

        chunks.append(remaining[:cut].rstrip())
        remaining = remaining[cut:].lstrip()

    if remaining.strip():
        chunks.append(remaining.strip())

    return chunks if chunks else [message]
