"""Pure rendering: `Digest` → Telegram HTML string.

Why "pure": no LLM, no network, no SQLite. Same Digest in → same HTML
out, always. This makes length-policy testing easy — just call
`render_digest(digest)` and measure the result.

HTML vs Markdown:
  We use Telegram's HTML parse_mode (set in TelegramConfig). Compared
  to MarkdownV2 it has fewer "characters you must escape or Telegram
  rejects your message" traps. Supported tags we use:
    <b>     bold                (section headers, item titles)
    <a>     clickable link      (source URL at end of each entry)
    <i>     italic              (footer / legend)
  See https://core.telegram.org/bots/api#html-style for the full list.

Structure of the rendered digest:
    <header: 🔬 Topic — Date>

    <intro paragraph, plain text>

    📋 <b>Papers</b>

    📌 1. <b>Title</b>
    <summary paragraph>
    🔗 <a href="url">url</a>

    ━━━━━━━━━━━━━━━

    📌 2. ...

    ✨ <i>Generated by: model_used</i>

Sections appear only when they have at least one entry. Entries within
a section are already in rank-descending order (set by the summarizer,
which preserved ranking-stage order).

Titles are kept in their original language per user's preference — no
translation is done here, and this file never touches the summary
strings beyond wrapping them into the layout.
"""

from __future__ import annotations

import html
from collections import defaultdict

from ..models.digest import Digest, DigestEntry

_SECTION_ORDER: tuple[str, ...] = ("PAPERS", "BLOGS", "PODCASTS", "SOCIAL")
_SECTION_EMOJI: dict[str, str] = {
    "PAPERS": "📋", "BLOGS": "📝", "PODCASTS": "🎙", "SOCIAL": "💬",
}
_SEPARATOR = "━━━━━━━━━━━━━━━"


def _esc(text: str) -> str:
    """Escape user/LLM text for HTML parse_mode.

    Telegram HTML requires `&`, `<`, `>` escaped inside text nodes. We
    never put raw LLM output into the message without passing it
    through here — a stray `<` would make Telegram reject the whole
    message with 400 Bad Request.
    """
    return html.escape(text, quote=False)


def _render_entry(idx: int, entry: DigestEntry) -> str:
    """Render one numbered entry block.

    Args:
        idx: 1-based position inside the section.
        entry: The DigestEntry to render.

    Returns:
        A multi-line HTML string ending WITHOUT a trailing newline.
    """
    item = entry.item
    title = _esc(item.title)
    url = str(item.url)

    marker = "📖" if item.full_text_accessible else "📌"
    title_line = f"{marker} {idx}. <b>{title}</b>"
    summary = _esc(entry.summary.strip())
    link_line = f'🔗 <a href="{_esc(url)}">{_esc(url)}</a>'

    return f"{title_line}\n\n{summary}\n{link_line}"


def _render_section(section: str, entries: list[DigestEntry]) -> str:
    """Render one section header + its entries, separated by visual dividers."""
    emoji = _SECTION_EMOJI.get(section, "📄")
    header = f"{emoji} <b>{section.title()}</b>"
    rendered = [_render_entry(i, e) for i, e in enumerate(entries, start=1)]
    body = f"\n\n{_SEPARATOR}\n\n".join(rendered)
    return f"{header}\n\n{body}"


def _group_by_section(entries: list[DigestEntry]) -> dict[str, list[DigestEntry]]:
    """Preserve the incoming (rank-ordered) order inside each section."""
    grouped: dict[str, list[DigestEntry]] = defaultdict(list)
    for e in entries:
        grouped[e.section].append(e)
    return grouped


def _ordered_sections(grouped: dict[str, list[DigestEntry]]) -> list[str]:
    """Canonical order first, then any unknown sections at the end."""
    known = [s for s in _SECTION_ORDER if s in grouped]
    unknown = [s for s in grouped if s not in _SECTION_ORDER]
    return known + unknown


def render_header(digest: Digest) -> str:
    """Top-of-message title line. Kept a standalone helper so length
    policy can measure it independently of the body."""
    return f"<b>🔬 {_esc(digest.topic)} — {digest.digest_date.isoformat()}</b>"


def render_footer(digest: Digest) -> str:
    """Bottom attribution line. Prints the actually-used model so the
    user can compare outputs across the `test_models` rotation."""
    return f"<i>✨ Generated by: {_esc(digest.model_used)}</i>"


def render_digest(digest: Digest) -> str:
    """Full render: header + intro + sections + footer.

    Args:
        digest: Fully summarized digest from the summarization layer.

    Returns:
        One HTML string ready to pass to the Telegram API. May exceed
        the Telegram 4096-char hard limit — length policy in deliver.py
        handles that; this function doesn't truncate.

    Called by:
        `deliver.prepare_messages`, once per degradation attempt.
    """
    parts: list[str] = [render_header(digest)]
    if digest.intro.strip():
        parts.append(_esc(digest.intro.strip()))

    grouped = _group_by_section(digest.entries)
    for section in _ordered_sections(grouped):
        parts.append(_render_section(section, grouped[section]))

    # Legend appears only when at least one entry got the 📖 marker, so
    # digests with no accessible items don't show an unexplained icon key.
    if any(e.item.full_text_accessible for e in digest.entries):
        parts.append("<i>📖 = full text accessible for follow-up</i>")

    parts.append(render_footer(digest))
    return "\n\n".join(parts)


def render_with_top_n(digest: Digest, n: int) -> str:
    """Render only the top-N entries (by the order already on the digest).

    Used by length-policy degradation Levels 1-2: progressively shrink
    `n` until the rendered message fits, down to `min_items_floor`.
    """
    shrunk = digest.model_copy(update={"entries": digest.entries[:n]})
    return render_digest(shrunk)


def split_message(message: str, hard_limit: int) -> list[str]:
    """Split an over-long HTML message into chunks that each fit under hard_limit.

    Strategy per cut:
      - Try to split at a blank-line boundary (`\\n\\n`) before hard_limit.
      - Fall back to the last single newline before the limit.
      - Last resort: hard character cut.

    Returns `[message]` unchanged if it already fits.
    """
    chunks: list[str] = []
    remaining = message

    while len(remaining) > hard_limit:
        cut = remaining.rfind("\n\n", 0, hard_limit)
        if cut <= 0:
            cut = remaining.rfind("\n", 0, hard_limit)
        if cut <= 0:
            cut = hard_limit

        chunks.append(remaining[:cut].rstrip())
        remaining = remaining[cut:].lstrip()

    if remaining.strip():
        chunks.append(remaining.strip())

    return chunks if chunks else [message]
